Network IOCs for March 2021 Exchange Vulnerabilities.
cisagov/CHIRP pull request #18
Opened 2021-03-20 18:54 UTC by greyl0cke

Added malicious IP addresses associated with the March 2021 Exchange vulnerabilities. (CVE-2021-26855, CVE-2021-26857, CVE-2021-26858, and CVE-2021-27065)

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## 📷 Screenshots (if appropriate) ##

## ✅ Checklist ##

* [ ] This PR has an informative and human-readable title.
* [ ] Changes are limited to a single goal - _eschew scope creep!_
* [ ] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
* [ ] All relevant type-of-change labels have been added.
* [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [ ] Tests have been added and/or modified to cover the changes in this PR.
* [ ] All new and existing tests pass.

2021-03-20 20:13 UTC, DeemOnSecurity commented
I see you’re trying to pass the CI checks. Please check out the instructions in [CONTRIBUTING.md](CONTRIBUTING.md) to see how to run pre-commit checks on your local machine. This will let precondition actually modify the files to make the fix.

2021-03-20 20:15 UTC, DeemOnSecurity requested changes
Please put a link to the report that has these IoCs in the description field

2021-03-20 20:25 UTC, greyl0cke commented
> 
> 
> I see you’re trying to pass the CI checks. Please check out the instructions in [CONTRIBUTING.md](CONTRIBUTING.md) to see how to run pre-commit checks on your local machine. This will let precondition actually modify the files to make the fix.

Thanks, I'll re-read the doc I'm sure I missed something.  

This was actually my first pull request, apologies for the confusion.

2021-03-20 20:40 UTC, greyl0cke commented
> 
> 
> Please put a link to the report that has these IoCs in the description field

The 185.56.81/24 net was something we saw with clients that had been compromised.
![image](https://user-images.githubusercontent.com/59586489/111884912-eed77a80-899a-11eb-9228-a5c0bc00ab3e.png)



You can find the others from the report from Volexity.
https://www.volexity.com/blog/2021/03/02/active-exploitation-of-microsoft-exchange-zero-day-vulnerabilities/

103.77.192.219
    104.140.114.110
    104.250.191.110
    108.61.246.56
    149.28.14.163
    157.230.221.198
    167.99.168.251
    185.250.151.72
    192.81.208.169
    203.160.69.66
    211.56.98.146
    5.254.43.18
    80.92.205.81

2021-03-21 02:09 UTC, DeemOnSecurity requested changes
Once the previous change request has been fulfilled (a link to the volexity report in the description field of the indicator) and this is passing pre-commit checks I will merge with main

2021-03-21 04:07 UTC, greyl0cke commented
> 
> 
> Once the previous change request has been fulfilled (a link to the volexity report in the description field of the indicator) and this is passing pre-commit checks I will merge with main

I changed the description and included the Alert from CISA as that has the exact same info as the Volexity blog post.  This is also passing pre-commit checks now but I'm not sure what to do with the first two commits that failed.

2021-03-22 02:19 UTC, DeemOnSecurity approved these changes
Looks great! Thank you for your contribution @greyl0cke

2021-03-22 02:20 UTC, merged