Added indicator for AA21062A and updated iocs.yaml
cisagov/CHIRP pull request #29
Opened 2021-03-28 23:51 UTC by greyl0cke

Compiled IOCs in AA21-062A into a single alert.  Removed network addresses associated with this alert from iocs.yaml and added them to the alert indicator.

2021-03-31 01:51 UTC, DeemOnSecurity requested changes
The regular expressions on lines 130, 161 will not work. If you want to match any number of any character, regular expressions need `.*`, meaning: `.` match any character `*` zero to any number of times. Once this change is made I will merge

2021-03-31 01:52 UTC, DeemOnSecurity commented on indicators/AA21062A.yaml
> +  event.event_data: "~= *ServerInfo~*/*"
Should be "~= .*ServerInfo~.*/.*"

2021-03-31 01:53 UTC, DeemOnSecurity commented on indicators/AA21062A.yaml
> +  event.event_data: "~= *System.InvalidCastException*"
Should be `"~= .*System.InvalidCastException.*"`

2021-03-31 07:23 UTC, greyl0cke commented on indicators/AA21062A.yaml
> +  event.event_data: "~= *ServerInfo~*/*"
corrections made.

2021-03-31 07:24 UTC, greyl0cke commented on indicators/AA21062A.yaml
> +  event.event_data: "~= *System.InvalidCastException*"
Corrections made.

thanks again for pointing these out.  It was hard to test these since event log detections aren't working yet.

2021-04-01 01:26 UTC, DeemOnSecurity approved these changes
Works in testing. Thank you for your contribution.

2021-04-01 01:26 UTC, merged

2021-04-04 17:57 UTC, hcharnell7 commented
That's great #29

2021-04-04 18:04 UTC, lindacorbett reviewed
I don't realy no what to write and sumite