Non-zero Exit on IOC's Discovered in Non-interactive Mode
cisagov/CHIRP pull request #33
Opened 2021-04-06 18:26 UTC by d33bs

# Non-zero Exit on IOC's Discovered in Non-interactive Mode #

## 🗣 Description ##

Seeks IOC detection count from run and exits with non-zero status in non-interactive mode, retaining existing functionality in interactive mode. Addresses #31 

## 💭 Motivation and context ##

Common tooling in automatic workflows involves using non-zero exit codes to enable decision making after process completion. Using additional exit codes enhances CISA CHIRP's ability to be used within these contexts.

## 🧪 Testing ##

Used pre-commit to ensure proper conformance with linting and style.

Used the following against the code related to this PR to test various scenarios:
```shell
# non-interactive mode with non-zero exit (CHIRP self-detects IOC's when targeting itself)
python chirp.py -p yara -t c:\\chirp\\** -o chirp_result -l debug --non-interactive

# non-interactive mode with zero exit (no detections)
python chirp.py -p yara -t c:\\no_ioc_dir\\** -o chirp_result -l debug --non-interactive

# interactive mode with zero exit after prompt
python chirp.py -p yara -t c:\\no_ioc_dir\\** -o chirp_result -l debug
```

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
* [ ] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
* [] Tests have been added and/or modified to cover the changes in this PR.
* [x] All new and existing tests pass.

2021-04-07 12:57 UTC, DeemOnSecurity commented
@d33bs i will review this evening and merge the change with changes for v1.0.6

2021-04-07 12:59 UTC, d33bs commented
@DeemOnSecurity Sounds good, thank you!

2021-04-07 20:45 UTC, DeemOnSecurity requested changes
See my review comments

2021-04-07 20:45 UTC, DeemOnSecurity commented on README.md
> +## Non-interactive Mode
This should be triple hashed, as we use the double hash for section headers of our README

2021-04-07 20:45 UTC, DeemOnSecurity commented on chirp.py
> +        time.sleep(2)
This sleep should now be unnecessary with the native logging library in use.

2021-04-07 20:45 UTC, DeemOnSecurity commented on chirp/common.py
> +                    70, "Discovered IoC's, please see output reports for more details."
As we're using the `COMPLETED` code (70) for these messages, we probably want to change our default log level when non-interactive mode is invoked to only display 70+ logs, leaving the `-v` switch for verbose-ness if a user wants to run in non-interactive mode but wants full output.

2021-04-09 19:35 UTC, d33bs commented
Thank you for the comments @DeemOnSecurity ! Pushed another commit to address them.

2021-04-12 18:28 UTC, DeemOnSecurity approved these changes

2021-04-12 18:29 UTC, merged